[project]
name = "cli-weight"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=14.3.3",
    "sqlmodel>=0.0.37",
]


[project.scripts]
weightcli = "main:main"
